### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by fredzannarbor** [groq/groq-python#17]
(bookpublisherGPT) fred:bookpublishergpt$ mkvirtualenv groq
created virtual environment CPython3.10.9.final.0-64 in 847ms
  creator CPython3Posix(dest=/Users/fred/.virtualenvs/groq, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/fred/Library/Application Support/virtualenv)
    added seed packages: pip==23.3.1, setuptools==68.2.2, wheel==0.41.3
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /Users/fred/.virtualenvs/groq/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/fred/.virtualenvs/groq/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/fred/.virtualenvs/groq/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/fred/.virtualenvs/groq/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/fred/.virtualenvs/groq/bin/get_env_details
(groq) fred:bookpublishergpt$ pip install groq
Collecting groq
  Downloading groq-0.4.1-py3-none-any.whl.metadata (12 kB)
Collecting anyio<5,>=3.5.0 (from groq)
  Downloading anyio-4.3.0-py3-none-any.whl.metadata (4.6 kB)
Collecting distro<2,>=1.7.0 (from groq)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx<1,>=0.23.0 (from groq)
  Downloading httpx-0.27.0-py3-none-any.whl.metadata (7.2 kB)
Collecting pydantic<3,>=1.9.0 (from groq)
  Downloading pydantic-2.6.2-py3-none-any.whl.metadata (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 583.0 kB/s eta 0:00:00
Collecting sniffio (from groq)
  Downloading sniffio-1.3.0-py3-none-any.whl.metadata (3.6 kB)
Collecting typing-extensions<5,>=4.7 (from groq)
  Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting idna>=2.8 (from anyio<5,>=3.5.0->groq)
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting exceptiongroup>=1.0.2 (from anyio<5,>=3.5.0->groq)
  Downloading exceptiongroup-1.2.0-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi (from httpx<1,>=0.23.0->groq)
  Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->groq)
  Downloading httpcore-1.0.4-py3-none-any.whl.metadata (20 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->groq)
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting annotated-types>=0.4.0 (from pydantic<3,>=1.9.0->groq)
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.16.3 (from pydantic<3,>=1.9.0->groq)
  Downloading pydantic_core-2.16.3-cp310-cp310-macosx_10_12_x86_64.whl.metadata (6.5 kB)
Downloading groq-0.4.1-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 612.9 kB/s eta 0:00:00
Downloading anyio-4.3.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.6/85.6 kB 800.5 kB/s eta 0:00:00
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading httpx-0.27.0-py3-none-any.whl (75 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 1.0 MB/s eta 0:00:00
Downloading httpcore-1.0.4-py3-none-any.whl (77 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 748.6 kB/s eta 0:00:00
Downloading pydantic-2.6.2-py3-none-any.whl (394 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.9/394.9 kB 910.6 kB/s eta 0:00:00
Downloading pydantic_core-2.16.3-cp310-cp310-macosx_10_12_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 822.9 kB/s eta 0:00:00
Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Downloading idna-3.6-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 831.5 kB/s eta 0:00:00
Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 1.8 MB/s eta 0:00:00
Downloading h11-0.14.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 978.4 kB/s eta 0:00:00
Installing collected packages: typing-extensions, sniffio, idna, h11, exceptiongroup, distro, certifi, annotated-types, pydantic-core, httpcore, anyio, pydantic, httpx, groq
Successfully installed annotated-types-0.6.0 anyio-4.3.0 certifi-2024.2.2 distro-1.9.0 exceptiongroup-1.2.0 groq-0.4.1 h11-0.14.0 httpcore-1.0.4 httpx-0.27.0 idna-3.6 pydantic-2.6.2 pydantic-core-2.16.3 sniffio-1.3.0 typing-extensions-4.9.0

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
(groq) fred:bookpublishergpt$ python classes/Codexes/Tools/toy-groq-complete.py Traceback (most recent call last):
  File "/Users/fred/bin/nimble/bookpublisherGPT/classes/Codexes/Tools/toy-groq-complete.py", line 6, in <module>
    from groq.llmcloud import Models
ModuleNotFoundError: No module named 'groq.llmcloud'
Python 3.10.9 (main, Dec 15 2022, 18:25:35) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import groq
>>> from groq import llmcloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'llmcloud' from 'groq' (/Users/fred/.virtualenvs/groq/lib/python3.10/site-packages/groq/__init__.py)
>>> from groq.llmcloud import Completion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

**Comment by rattrayalex** [comment]
Where in the docs did you see references to `groq.llmcloud`?

**Comment by fredzannarbor** [comment]
In the quickstart -- but I now am realizing that I want to be in the PyPi
documentation

https://pypi.org/project/groq/

[image: image.png]
---
Fred Zimmerman, Publisher
Nimble Books LLC
The AI Lab for Book-Lovers <http://NimbleBooks.com>

**Comment by gabrielchua** [comment]
`qroq.llmcloud` is used here: https://docs.api.groq.com/md/tutorials/python.groqapi.html

**Comment by hozen-groq** [comment]
For the latest documentation, please visit [https://console.cloud.groq.com/](https://console.cloud.groq.com/).

**Comment by fredzannarbor** [comment]
https://console.cloud.groq.com/

This site can’t be reached

Check if there is a typo in console.cloud.groq.com.
DNS_PROBE_FINISHED_NXDOMAIN
---
Fred Zimmerman, Publisher
Nimble Books LLC
The AI Lab for Book-Lovers <http://NimbleBooks.com>

**Comment by hozen-groq** [comment]
Whoops! Totally gave you the wrong link there. Forgive me, Fred! The correct link is the following: [https://console.groq.com/](https://console.groq.com/ )

**Comment by fredzannarbor** [comment]
THanks!  Just as a reminder, the reason I got confused was because my
welcome email landed me on some sort of page that was maybe outdated?  Not
sure, but the "how to get to the docs" piece was a little wobbly.
---
Fred Zimmerman, Publisher
Nimble Books LLC
The AI Lab for Book-Lovers <http://NimbleBooks.com>

**Comment by hozen-groq** [comment]
Thank you for that feedback, Fred! We just transitioned over to the new API console site, so apologies for the wobbliness you had to experience... the team is ironing out the wobbles. In the meantime, now that you're properly set up, I wish you happy exploring with Groq! 🚀
