### ISSUE TITLE
Embeddings Functionality Active?

### ISSUE THREAD

**Issue by djokester** [groq/groq-python#96]
`client.embeddings.create(input="Hello",  model="llama3-8b-8192", encoding_format="float")`

Results in a timeout error

```
Traceback (most recent call last):
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/groq/_base_client.py", line 951, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/groq/resources/embeddings.py", line 79, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/groq/_base_client.py", line 1225, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/groq/_base_client.py", line 920, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/groq/_base_client.py", line 960, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/groq/_base_client.py", line 1051, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/groq/_base_client.py", line 960, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/groq/_base_client.py", line 1051, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/djokester/anaconda3/envs/groqeval/lib/python3.11/site-packages/groq/_base_client.py", line 970, in _request
    raise APITimeoutError(request=request) from err
groq.APITimeoutError: Request timed out.
```

**Comment by gradenr** [comment]
Thanks for your interest.  We are still working on embeddings support and it is not currently available.  Please follow our  [social media](https://x.com/GroqInc) or join our [discord](https://discord.gg/WANYA6kR) for announcements.

**Comment by renewfresho** [comment]
I'm getting "The model `nomic-embed-text-v1.5` does not exist or you do not have access to it when I use the example at https://github.com/groq/groq-python/blob/8bcc29478315e59c2a9a730ade712511e0540f7b/examples/embedding.py Weird that the example exists but the functionality doesn't work. 

I noticed that the [client source code](https://github.com/groq/groq-python/blob/main/src/groq/resources/embeddings.py) includes "nomic-embed-text-v1_5" (underscore instead of period). I tried that as well and had the same error.  

Embeddings over groq is super exciting. very looking forward to when it's supported

**Comment by hozen-groq** [comment]
@renewfresho Hi there! 👋 Exciting that you're excited about embeddings! Our team is still working on enabling this, but it's coming soon. If you haven't already, please join our developer community on [Discord](https://discord.gg/invite/groq) to keep up with announcements - stay tuned!
